- hosts: cherry-gw
  tasks:

#    - name: get file stat to be able to perform check in the following task
#      local_action: stat path=files/cherry-gw/firewall/use.this
#      register: file
#      ignore_errors: True

#    - name: copy file if it exists
#      copy: src=files/cherry-gw/firewall/{{ item  }} dest=/tmp/ owner=root group=root mode=644 backup=yes
#      when: file.stat.exists
#      with_items:
#        - firewall
#        - firewall.cherry
#        - firewall.md5
#      become: yes


    - name: Get remote MD5 for firewall-config
      stat: path=/var/lib/firewall
      register: fw_remote_firewall
    - name: Get remote MD5 for firewall script
      stat: path=/var/lib/firewall.cherry
      register: fw_remote_firewall_cherry


    - name: Get local md5sum firewall-config
      local_action: stat path=files/cherry-gw/firewall/firewall 
      register: fw_local_firewall
    - name: Get local md5sum firewall-config
      local_action: stat path=files/cherry-gw/firewall/firewall.cherry 
      register: fw_local_firewall_cherry


    - name: Copy "firewall" if md5sum no equal
      copy: src=files/cherry-gw/firewall/firewall dest=/var/lib/ owner=root group=root mode=644 backup=yes
      when: fw_local_firewall.stat.md5 != fw_remote_firewall.stat.md5
      become: yes

    - name: Copy if "firewall.cherry" checksum no equal
      copy: src=files/cherry-gw/firewall/firewall.cherry dest=/var/lib/ owner=root group=root mode=744 backup=yes
      when: fw_local_firewall_cherry.stat.md5 != fw_remote_firewall_cherry.stat.md5
      become: yes


    - name: Copy "firewall.md5" if script modified
      copy: src=files/cherry-gw/firewall/firewall.md5 dest=/var/lib owner=root group=root mode=655
      when: fw_local_firewall_cherry.stat.md5 != fw_remote_firewall_cherry.stat.md5
      become: yes

    - name: Run firewall after copy file
      command: '/var/lib/firewall.cherry'
      when: fw_local_firewall_cherry.stat.md5 != fw_remote_firewall_cherry.stat.md5 or fw_local_firewall.stat.md5 != fw_remote_firewall.stat.md5
      become: yes
      register: out

#    - debug: var=out.stdout_lines
#    - debug: var=fw_conf_local