- hosts: cherry-gw
  vars:
      cherry_vip: {
          remote: /etc/squid3/cherry_vip,
          local: files/cherry-gw/squid/cherry_vip
          }
  tasks:


    - name: Get remote MD5 for CherryVIP
      stat: path={{ cherry_vip.remote }}
      register: cherry_vip_remote

    - name: Get local md5sum CherryVIP
      local_action: stat path={{ cherry_vip.local }}
      register: cherry_vip_local

    #- name: Copy "firewall" if md5sum no equal
    #  copy: src={{ cherry_vip.local }} dest=/etc/squid3/ owner=root group=root mode=644 backup=yes
    #  when: cherry_vip_remote.stat.md5 != cherry_vip_local.stat.md5 or not cherry_vip_remote.stat.exists
    #  become: yes
    - template: src=templates/cherry_vip.j2 dest=/etc/squid3/cherry_vip_new
      become: yes

    - debug: var=cherry_vip_remote.stat.md5

