- hosts: all
  tasks:
   - name: Update Packages in CentOS
     yum: name=* state=latest
     when: ansible_os_family == "RedHat"
     become: yes

   - name: Upgrade package in Ubuntu 
     apt: update_cache=yes upgrade=safe
     when: ansible_os_family == "Debian"
     become: yes
