#!/bin/sh
#################################################################
######## FireWall Config For CherryPie by Depeche 2009 ##########
#				    			  	#
# For Tree Interface Routing				       	#
#  	eth0 - local						#
#	eth1 - external network					#
#################################################################
#                !!! Use Path-O-Matic'a !!! 	        	#
#################################################################
#################################################################

#################################################################
#
######## Colorized ########
Color_Blue="\033[1;36m"
Color_Def="\033[1;0m"
Color_Red="\033[1;31m"
Color_Gren="\033[1;32m"
Color_Grey="\033[1;30m"
Color_Yellow="\033[1;33m"
Color_Pink="\033[1;35m"
###########################

IPTABLES="/sbin/iptables"
TC=/sbin/tc
IPROUTE2=/sbin/ip

depeche_cherry="192.168.15.51"

# 1 - use  0 - not use


# Log
CONNECTION_TRACKING="0"
DEBUG="0"
SCAN_LOG="1"
BAD_FLAG="1"
FLAG_LOG="1"
SMB_TARPIT_LOG="1"

# Interface
LAN_INTERFACE="eth0"
LAN_IPADDR="192.168.15.254"
LAN_ADDRESSES="192.168.15.0/24"
LAN_NETWORK="192.168.15.0"
LAN_NETMASK="255.255.255.0"
LAN_BROADCAST="192.168.15.255"
LAN_MULTICAST="255.255.255.255"

EXT_INTERFACE="eth1"
EXT_IPADDR="95.131.89.25"
EXT_ADDRESSES="95.131.89.16/28"
EXT_NETWORK="95.131.89.16"
EXT_NETMASK="255.255.255.240"
EXT_BROADCAST="95.131.89.31"
GETAWEY_IPADDR="95.131.89.17"

GUEST_WIFI_INTERFACE="eth0.2"
GUEST_WIFI_IPADDR="192.168.12.254"
GUEST_WIFI_ADDRESSES="192.168.12.0/24"
GUEST_WIFI_NETWORK="192.168.12.0"
GUEST_WIFI_NETMASK="255.255.255.0"
GUEST_WIFI_BROADCAST="192.168.12.255"
GUEST_WIFI_MULTICAST="255.255.255.255"


VOIPSRV_NETWORK="10.10.5.0/24"

NAMESERVERS="95.131.89.18 95.131.90.18" 

POP_SERVER="95.131.90.18"
SMTP_SERVER="95.131.90.18"

EXTERNAL_POP_USERS="192.168.15.0/24"
NTP_USERS="192.168.15.0/26"

ICQ_DROP_USER="192.168.15.254"
ICQ_USERS="192.168.15.0/26"

		    
### Bank Clients ####
#
Bank_USER="192.168.15.129 192.168.15.23"
SberBank_SERVER="194.186.207.189"
NatcPromBank_SERVER="212.13.97.9"
#
#####################

NETUP_SRV="95.131.89.21"
NETUP_USER="192.168.15.50 192.168.15.53 192.168.15.54"

ADMIN="192.168.15.51 192.168.15.61 192.168.15.54 192.168.15.50 192.168.15.42 192.168.15.191 192.168.15.187 192.168.15.165"
# 124 - notebook
PRINT_MACHINES="192.168.15.247"

VNC_PORT="5900"
VNC_USER="213.26.67.10"
VNC_CLIENT="192.168.4.42"

SSH_OUT_USERS="192.168.15.51 192.168.15.42"
OpenVPN_USER="192.168.15.23"

VIDEO_SRV="192.168.15.249"
####################
#
FULL_ACCESS="	10.10.5.1      10.10.5.2     10.10.5.3     10.10.5.4     10.10.5.5      10.10.5.8  10.10.5.9	10.10.5.17 
		10.10.5.14	192.168.15.8	10.10.5.18	192.168.15.221	192.168.15.51	192.168.15.23 192.168.15.24
		192.168.15.4	192.168.15.53	10.10.5.16	192.168.15.9	192.168.15.26	192.168.15.247	192.168.15.15	
		192.168.15.58	192.168.15.57 	10.10.5.50 	192.168.15.36 	192.168.15.55 	192.168.15.63 	192.168.15.145
		192.168.15.50 	192.168.15.60"
# 21 Timoshenko
# 15.145 Nuvera288
# 15.44 for RDP
# 60 - Kozlov
# 15.58 - m200-billing
# 57 - my phone
# 15.100 - телефон
# !!! Remove 15.54 15.119 15.220 15.96
####################

####################
# PPTP Users
PPTP_USERS="192.168.15.29 192.168.15.49 192.168.15.197"
PPTP_SERVER="vpn.monorhythm.ru"


######

USE_TEMPLATE_BLOCK="0"
TEMPLATE_BLOCK_USERS="192.168.15.103 192.168.15.75 192.168.15.47"
##############################################

####################
WEB_NO_PROXY="192.168.15.21 192.168.15.20"
#
#
####################
MS_ACTIVATE_ACCESS="0"
MS_ACTIVATE_USER="192.168.0.0/16"
MS_ACTIVATE_IP="131.107.115.0/24"

#BitTorrent="192.168.3.43"

GTEL_NET="95.131.90.0 95.131.89.0"
NAGIOS="95.131.90.50"

VOIP_SERVERS="95.131.90.2 95.131.90.4 95.131.89.12"

USE_IPPERF="1"
#########################################################################################################

LOOPBACK="127.0.0.0/8"
CLASS_A="10.0.0.0/8"
CLASS_B="172.16.0.0/12"
CLASS_C="192.168.0.0/16"
CLASS_D_MULTICAST="224.0.0.0/4"
CLASS_E_RESERVED_NET="240.0.0.0/5"
BROADCAST_SRC="0.0.0.0"
BROADCAST_DEST="255.255.255.255"

PRIVPORTS="0:1023"
UNPRIVPORTS="1024:65535"

### function section #######

check_sum () {

Sum=`/usr/bin/md5sum /var/lib/firewall.cherry | awk '{print $1}'`
Sum_Now=`cat /var/lib/firewall.md5 | awk '{print $1}'`

if [ "$Sum" != "$Sum_Now" ]; then
    sleep 5
    echo -e "Firewall $Color_Gren Starting $Color_Def"
    echo "$Sum <-> $Sum_Now"
    exit 1
fi
}

show_format () {
    for i in $@; do
	if [ "$z" == "3" ]; then
	    echo; z=0
	fi
	echo -ne "\t\t${Color_Grey}${i}${Color_Def} "
	let "z += 1"	
    done
    echo
}

echo_ok () {
    echo -e "\t${Color_Gren}Ok${Color_Def}"
}

